# Generated by Django 4.0.5 on 2022-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsite', '0002_alter_cars_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(default='car'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.TextField(default='petrol'),
        ),
        migrations.AddField(
            model_name='cars',
            name='luggage',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='seats',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.TextField(default='manual'),
        ),
    ]
