# Generated by Django 4.0.5 on 2022-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsite', '0003_cars_description_cars_fuel_cars_luggage_cars_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(null=True, to='mycarsite.comments'),
        ),
    ]
