# Generated by Django 4.0.5 on 2022-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsite', '0004_alter_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
