# Generated by Django 4.0.5 on 2022-06-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsite', '0006_alter_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mycarsite.tags'),
        ),
    ]
