# Generated by Django 4.0.5 on 2022-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarsite', '0007_alter_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='tagsss', to='mycarsite.tags'),
        ),
    ]
